### PR TITLE
Bump Qt and CI script versions, fix macOS support, and drop support for qmake

### PR DESCRIPTION
**Pull request by Cuperino**
Bumping the Qt acquisition script should fix build errors in CI.

### CODE REVIEW

**Comment by Cuperino** [comment]
I've bumped the versions to the latest micro versions available. Nevertheless, the Qt 5s fail to build, with linker undefined symbol errors that occur after bumping `jurplel/install-qt-action`.

**Comment by Shatur** [comment]
Looks like on MacOS it tries to build it for ARM, but Qt binaries are for x86.

**Comment by Cuperino** [comment]
@Shatur I got CI fixed for all systems using CMake. I couldn't get the qmake build to work with Windows, I don't normally work on Windows and QMake is being phased out anyways, so I opted to remove those builds from CI in the end.

Feel free to re-add them and fix whatever issue is left. Here is the commit that got the closest to getting qmake to work everywhere: 57525e01402bd21c36225858147470861b80f720

**Comment by Shatur** [comment]
I'm on board with removing qmake. Could you remove the qmake file completely?

**Comment by Cuperino** [comment]
Done. All files pertaining qmake have been removed.

**Comment by Shatur** [comment]
Thank you!

**Pull request merged**
