### PR TITLE
Fix: Prevent crash on Wayland when using Qt 6

### PR DESCRIPTION
**Pull request by Cuperino**
x11Interface is not guaranteed have been instantiated under a Wayland session, this led apps to be terminated by signal SIGSEGV (Address boundary error)

### CODE REVIEW

**Comment by Cuperino** [comment]
Qt mirrors need to be updated for CI to function. My code didn't cause those failures.

**Comment by Shatur** [comment]
Could you bump the install Qt action?

**Comment by Shatur** [comment]
Could you rebase to the latest master?

**Comment by Cuperino** [comment]
Done

**Comment by Cuperino** [comment]
#96 solves the same issue as this PR does. I personally like this solution better, but i wrote it, so I'm biased.

**Comment by dbermond** [comment]
> #96 solves the same issue as this PR does. I personally like this solution better, but i wrote it, so I'm biased.

Your looks better, since it uses one less checking for `nullptr`.

**Comment by Shatur** [comment]
Thanks, merging then!

**Pull request merged**
